version = 1

[[analyzers]]
  name = "javascript"
  enabled = true
  
  [analyzers.meta]
   plugins = ["react"]

exclude_patterns = [
  "node_modules/**",
  "public/**",
  "coverage/**",
  "styled-system/**"
]

test_patterns = [
  "__tests__/**",
]